name: Comment on the pull request

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        id: downloader
        uses: actions/download-artifact@v4
        with:
          name: outputs
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set up PR number
        run: echo "PR_NUMBER=$(cat ./pr.txt)" >> $GITHUB_ENV

      - name: Format output
        id: formatter
        env:
          FLAG: ${{ secrets.FLAG }}
        run: |
          chmod +x ./format.sh
          ./format.sh ./valgrind.txt

      - name: Comment on PR
        uses: actions/github-script@v7
        id: commenter
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            github.rest.issues.createComment({
              issue_number: ${{ env.PR_NUMBER }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: fs.readFileSync('./output.md').toString()
            });
