name: Receive PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up outputs directory
        run: mkdir -p outputs

      - name: Store PR information
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo ${{ github.event.number }} > ./outputs/pr.txt

      - name: Install Valgrind
        run: |
          sudo apt update
          sudo apt install -y valgrind

      - name: Build
        run: make

      - name: Save Valgrind output
        run: valgrind --log-file=./outputs/valgrind.txt --leak-check=yes ./prog

      - name: Save all infos
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/
      